// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.startupRolloutPrefs.services.sync.bookmarks.buffer", true);
user_pref("app.normandy.user_id", "9ad62f77-1bb3-48aa-aea5-8ba85a4a35c1");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.backgroundErrors", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1573600937);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1573600577);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1573601579);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1573600697);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1573601057);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.E7CF176E110C211B", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 547);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1573600547);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{24581050-a964-40c1-b050-7f9167c08e41}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191016161957");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 1842);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20191016161957");
user_pref("browser.startup.homepage_override.mstone", "70.0");
user_pref("browser.startup.lastColdStartupCheck", 1573601566);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1573600549539");
user_pref("distribution.iniFile.exists.appversion", "70.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "9ba7e96ad3d44a18af2d485f24fd291f");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191016161957");
user_pref("extensions.lastAppVersion", "70.0");
user_pref("extensions.lastPlatformVersion", "70.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"981290fe-892e-4fcd-ae8e-d4f8ce01027c\",\"screenshots@mozilla.org\":\"acbc6a6c-68c9-4bfa-a167-21c39c0cc43c\",\"webcompat-reporter@mozilla.org\":\"8d9b8f58-6d49-4a1e-b310-b7710f8233e1\",\"webcompat@mozilla.org\":\"82bf0ac0-882c-49a2-b24b-5a2386fbead5\",\"fpdlpffext@forcepoint.com\":\"9b807693-99ae-45d0-a408-069d234ddc35\",\"default-theme@mozilla.org\":\"a469c844-65e8-4687-9e16-fd76e6866aef\",\"google@search.mozilla.org\":\"616e9b7a-308f-40d3-b67c-c97ec973aacf\",\"amazondotcom@search.mozilla.org\":\"c234630d-0f2c-4768-9305-e5f03447fe95\",\"bing@search.mozilla.org\":\"c5ae9a49-2e95-4f19-b2f8-343791976fcc\",\"ddg@search.mozilla.org\":\"05b86a8c-2eb1-47ec-a9d1-955b11b3569b\",\"ebay@search.mozilla.org\":\"1c8357e6-cd48-4aff-bc73-c86e921b3b05\",\"twitter@search.mozilla.org\":\"dcfec90c-22a3-4126-bb92-e76d632ca346\",\"wikipedia@search.mozilla.org\":\"07936b3d-cb53-4997-b252-69945e3b079b\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "70.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x0412");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "20.19.15.5063");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp-manager.buildID", "20191016161957");
user_pref("media.gmp-manager.lastCheck", 1573600687);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x0412");
user_pref("sanity-test.driver-version", "20.19.15.5063");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20191016161957");
user_pref("security.sandbox.content.tempDirSuffix", "{22ecf4e8-9342-4da5-acfb-28e650b88fc1}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{87a7c3dc-9ef2-455d-b5bb-307c860c760f}");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1573596764293\"");
user_pref("services.settings.last_update_seconds", 1573601573);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1573601573);
user_pref("services.settings.main.cfr-fxa.last_check", 1573601573);
user_pref("services.settings.main.cfr.last_check", 1573601573);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1573601573);
user_pref("services.settings.main.hijack-blocklists.last_check", 1573601573);
user_pref("services.settings.main.language-dictionaries.last_check", 1573601573);
user_pref("services.settings.main.normandy-recipes.last_check", 1573601573);
user_pref("services.settings.main.sites-classification.last_check", 1573601573);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1573601573);
user_pref("services.settings.main.whats-new-panel.last_check", 1573601573);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1573601565);
user_pref("toolkit.telemetry.cachedClientID", "42fe63c9-0506-4cf0-a111-778f9cde79a9");
user_pref("toolkit.telemetry.previousBuildID", "20191016161957");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
